language: scala
dist: xenial
jdk:
- openjdk11
- openjdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
script:
- git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
- git show --oneline --check
- sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
